project:
  type: website

website:
  title: "Quarto Live Documentation"
  description: "Interactive code blocks and exercises, powered by WebAssembly."
  sidebar:
    contents:
      - href: index.qmd
      - section: Getting Started
        contents:
          - getting_started/editor.qmd
          - getting_started/packages.qmd
          - getting_started/plotting.qmd
          - getting_started/readonly.qmd
      - section: Exercises and Grading
        contents:
          - exercises/exercises.qmd
          - exercises/hints.qmd
          - exercises/environments.qmd
          - exercises/autocomplete.qmd
          - exercises/localstorage.qmd
          - exercises/grading.qmd
          - exercises/gradethis.qmd
          - exercises/python.qmd
      - section: Interactive Documents and Tutorials
        contents:
          - interactive/reactivity.qmd
          - interactive/python.qmd
          - interactive/data.qmd
          - interactive/dynamic.qmd
          - interactive/define.qmd
      - section: Other Features
        contents:
          - other/tables.qmd
          - other/resources.qmd
          - other/html.qmd
          - other/python.qmd
          - other/slides.qmd

theme:
  light: default
  dark: darkly
