on:
  push:
    branches:
      - main

name: Render and Publish
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
    # environment:
    #   name: github-pages
    #   url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Netlify
        run: npm install netlify-cli -g
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install Jupyter
        run: python3 -m pip install jupyter
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
      - name: Install R packages
        run: Rscript -e 'install.packages(c("rmarkdown", "knitr"))'
      - name: Render Quarto Project
        uses: quarto-dev/quarto-actions/render@v2
        with:
          path: docs
      # - name: Deploy to GitHub Pages
      #   id: deployment
      #   uses: actions/deploy-pages@v4
      - name: Deploy to Netlify
        run: |
          netlify deploy \
            --prod \
            --dir docs/_site \
            --site ${{ secrets.NETLIFY_SITE }} \
            --auth ${{ secrets.NETLIFY_TOKEN }}
